# Generated by Django 4.1.7 on 2023-03-29 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_alter_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='Category',
        ),
    ]
